name: Build & Push Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  cpu:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cpu
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/labelgenius:cpu
            ghcr.io/${{ github.repository_owner }}/labelgenius:cpu-${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  cuda:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cuda
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/labelgenius:cuda
            ghcr.io/${{ github.repository_owner }}/labelgenius:cuda-${{ github.sha }}
          platforms: linux/amd64
